apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-application
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: app-2
            version: v1.0.0
  template:
    metadata:
      name: argo-temp-app
      labels:
        app.kubernetes.io/managed-by: argocd-applicationset
        version: "v1.2.3"
        customer: "argo-temp-app"
      annotations:
        notifications.argoproj.io/subscribe.on-deployed.newrelic: "1076073543"        
    spec:
      project: argo-proj
      source:
        repoURL: https://github.com/varunaroratest/argo_newrelic.git
        path: k8
        targetRevision: main        
      destination:
        server: https://kubernetes.default.svc
        namespace: argo-temp-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true          
