apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.newrelic: |
    apiURL: https://api.newrelic.com
    apiKey: $newrelic-apiKey
  defaultTriggers: |
    - on-deployed
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      send:
      - app-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy' and app.status.sync.status == 'Synced'
  template.app-deployed: |
    message: Application "{{ .app.metadata.name }}" has successfully deployed.
    newrelic:
      description: "{{ .app.metadata.name }}" Application "{{ .app.metadata.annotations.component }}" has successfully deployed with "{{ .app.metadata.annotations.version }}" version.

      
