apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.newrelic: |
    apiURL: https://api.newrelic.com
    apiKey: $newrelic-apiKey
  context: |
    argocdUrl: localhost:8080/argocd
  defaultTriggers: |
    - on-deployed
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy' and app.status.sync.status == 'Synced'
      send:
      - app-deployed      
  template.app-deployed: |
    message: Application has successfully deployed.
    newrelic:
      description: Application has successfully deployed
      revision: v4.2
      user: shaifali
      changelog: string
