apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app-pod
  labels:
    app: nodejs-app
spec:
  containers:
    - name: nodejsapp
      image: nginx
      ports:
        - containerPort: 3000
      env:
        - name: NEW_RELIC_NO_CONFIG_FILE
          value: "true"
        - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
          value: "true"
        - name: NEW_RELIC_LICENSE_KEY
          value: "41683e4227f1e68aa6801086080f8e78FFFFNRAL"
        - name: NEW_RELIC_APP_NAME
          value: "NodeJsApp"
