apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app-pod
  labels:
    app: nodejs-app
spec:
  containers:
    - name: nodejsapp
      image: nginx
      ports:
        - containerPort: 3000
      env:
        - name: NEW_RELIC_NO_CONFIG_FILE
          value: "true"
        - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
          value: "true"
        - name: NEW_RELIC_LICENSE_KEY
          value: "d9ac3b2ff8488fbbaac476d5d5b1b52a0564NRAL"
        - name: NEW_RELIC_APP_NAME
          value: "NodeJsApp"
