name: Add Secret to Azure Cluster

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  add_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        run: |
          az login --service-principal \
            --username ${{ secrets.CLIENT_ID }} \
            --password ${{ secrets.AZURE_CREDENTIALS }} \
            --tenant ${{ secrets.TENANT_ID }}
          az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
      - name: Add secret to cluster
        run: |
          kubectl apply -f node/k8/applicationSets/secret.yaml
