name: Add Secret to Azure Cluster

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  add_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          allow-no-subscriptions: true

      - name: Add secret to cluster
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az aks get-credentials --resource-group argoResource --name clusterkubernetes
            kubectl apply -f node/k8/secret.yaml
