name: Add Secret to Azure Cluster

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  add_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        run: |
          az login --service-principal \
            --username ${{ secrets.CLIENT_ID }} \
            --password ${{ secrets.AZURE_CREDENTIALS }} \
            --tenant ${{ secrets.TENANT_ID }}
          az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
      - name: Add secret to cluster
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az aks get-credentials --resource-group argoResource --name clusterkubernetes
            az account set --subscription=1e8ac8e0-f34d-4b6d-a8e8-2ba9e9894a13
            # kubectl apply -f node/k8/secret.yaml
