name: Add Secret to Azure Cluster

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  add_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        run: |
          az login --service-principal \
            --username ${{ secrets.CLIENT_ID }} \
            --password ${{ secrets.AZURE_CREDENTIALS }} \
            --tenant ${{ secrets.TENANT_ID }}
          az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
      
      # - name: Install kubectl
      #   uses: azure/kubectl@v1
      #   with:
      #     install-yaml: true

      # - name: Get secret value
      #   id: get_secret
      #   run: |
      #     secret_value=$(kubectl get secret argocd-notifications-secret -o jsonpath='{.data.newrelic-apiKey}' | base64 --decode)
      #     echo "Secret Value: $secret_value"
      
      - name: Add secret to cluster
        run: |
          kubectl apply -f k8/cm.yaml -n argocd
