name: Deploy Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v3
        id: install
      - name: Install argocd CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.5.8/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
          argocd login cd.argoproj.io --core
          # argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
          # ping localhost:8080/argocd
      # - name: Create namespace
      #   run: |
      #     kubectl create namespace testnamespace
      - name: Deploy application
        env:
          ARGOCD_SERVER: localhost:8080/argocd
          ARGOCD_USERNAME: admin
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        run: |
          cd node/k8/applicationSets
          # argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
          kubectl apply -f cm.yaml
          kubectl apply -f secret.yaml
          argocd app create argo-application --repo https://github.com/varunaroratest/argo_newrelic.git --path . --dest-server https://kubernetes.default.svc --dest-namespace default
          argocd app sync argo-application
