name: Add Secret to Azure Cluster

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  KUBECONFIG: "/home/runner/work/_temp/kubeconfig_1697215423700"
  ARGOCD_SERVER: localhost:8080/argocd
  ARGOCD_USERNAME: admin
  ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
  
permissions:
  id-token: write
  contents: read

jobs:
  add_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        run: |
          az login --service-principal \
            --username ${{ secrets.CLIENT_ID }} \
            --password ${{ secrets.AZURE_CREDENTIALS }} \
            --tenant ${{ secrets.TENANT_ID }}
          az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
          
      - uses: azure/aks-set-context@v3        
        with:
          resource-group: argoResource
          cluster-name: clusterkubernetes
          admin: "false"
          # use-kubelogin: "true"
          
      # - name: Install kubectl
      #   uses: azure/kubectl@v1
      #   with:
      #     install-yaml: true

      # - name: Get secret value
      #   id: get_secret
      #   run: |
      #     secret_value=$(kubectl get secret argocd-notifications-secret -o jsonpath='{.data.newrelic-apiKey}' | base64 --decode)
      #     echo "Secret Value: $secret_value"
      
      - name: Add secret to cluster
        run: |
          cd node/k8/applicationSets
          argocd login $ARGOCD_SERVER --username admin --password $ARGOCD_PASSWORD --insecure
          kubectl apply -f cm.yaml
          kubectl apply -f secret.yaml
          argocd app create argo-application --repo https://github.com/masterysystems/devops-poc-test-workflow.git --path . --dest-server https://kubernetes.default.svc --dest-namespace default
          argocd app sync argo-application
