name: Add Secret
on:
  workflow_dispatch:
env:
  KUBECONFIG: "/home/runner/work/_temp/kubeconfig_1697437857702"
  NEWRELIC_APIKEY: ${{ secrets.NEWRELIC_APIKEY }}
jobs:
  add_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Azure CLI
        run: |
          az login --service-principal \
            --username ${{ secrets.CLIENT_ID }} \
            --password ${{ secrets.AZURE_CREDENTIALS }} \
            --tenant ${{ secrets.TENANT_ID }}
          az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}          
      - uses: azure/aks-set-context@v3        
        with:
          resource-group: argoResource
          cluster-name: clusterkubernetes
          admin: "true"
          use-kubelogin: "true"   
      - name: Set up Azure CLI
        uses: azure/aks-set-context@v3
        with:
          creds: ${{ secrets.NEWRELIC_APIKEY }}
          resource-group: argoResource
          cluster-name: clusterkubernetes
     
      - name: Add secret to cluster
        env:
          NR_KEY: ${{ secrets.NEWRELIC_APIKEY }}
        run: |
          cd k8/ 
          # NRKEY=$(echo -n "${NR_KEY}" | base64 -w 0)
          # sed -e "s/{{NRKEY}}/$NRKEY/g" temp-secret.yaml > secret.yaml
          # sed -e "s/\$NR_KEY/$NR_KEY/g" temp-secret.yaml > secret.yaml
          # envsubst < temp-secret.yaml > secret.yaml
          # kubectl create secret generic newrelickey --from-literal=newrelic="$NR_KEY"
          # NR_KEY_SECRET=$(kubectl create secret generic newrelickey --from-literal=newrelic="$NR_KEY" --dry-run=client -o yaml)
          # echo "$NR_KEY_SECRET" > secret.yaml          
          kubectl apply -f cm.yaml
