name: vaultSecret
on:
  workflow_dispatch:
env:
  KUBECONFIG: "/home/runner/work/_temp/kubeconfig_1697437857702"
  # NEWRELIC_APIKEY: ${{ secrets.NEWRELIC_APIKEY }}
jobs:
  add_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Azure CLI
        run: |
          az login --service-principal \
            --username ${{ secrets.CLIENT_ID }} \
            --password ${{ secrets.AZURE_CREDENTIALS }} \
            --tenant ${{ secrets.TENANT_ID }}
          az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}          
      - uses: azure/aks-set-context@v3        
        with:
          resource-group: argoResource
          cluster-name: clusterkubernetes
          admin: "true"
          use-kubelogin: "true"        
     
      - name: Add secret to cluster        
        run: |
          cd k8/           
          kubectl apply -f appset.yaml
          kubectl apply -f cm.yaml
